In [1]:
import numpy as np

arr = np.zeros((2, 2))
print(arr)


[[0. 0.]
 [0. 0.]]


In [2]:
import numpy as np

arr = np.ones((4, 2))
print(arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:

arr = np.full((3, 4), 7)
print(arr)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [7]:

a = np.array([[5, 9, 3],
              [2, 7, 1]])

z = np.zeros_like(a)

print(z)


[[0 0 0]
 [0 0 0]]


In [9]:
a = np.array([[5, 9, 3],
              [2, 7, 1]])

z = np.ones_like(a)

print(z)

[[1 1 1]
 [1 1 1]]


In [10]:

new_list = [1, 2, 3, 4]

arr = np.array(new_list)
print(arr)


[1 2 3 4]


In [11]:

arr = np.arange(10, 50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:

arr = np.arange(9).reshape(3, 3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:

arr = np.random.random(30)

mean_value = arr.mean()

print("Array:", arr)
print("Mean:", mean_value)


Array: [0.62795263 0.44909993 0.08327866 0.00584865 0.85708944 0.83311326
 0.76852242 0.23499955 0.26882983 0.1723393  0.07400218 0.34618542
 0.12521576 0.30893901 0.61632323 0.50812177 0.97938814 0.27601795
 0.64708095 0.3825342  0.80801329 0.0597738  0.50184107 0.44015187
 0.48952347 0.16995153 0.74119437 0.16221237 0.12064147 0.87615513]
Mean: 0.43114468821554125


In [17]:
arr = np.random.random((10, 10))

min_value = arr.min()
max_value = arr.max()

print("Array:\n", arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Array:
 [[0.11476713 0.00269996 0.17580979 0.06974004 0.83790097 0.99306525
  0.72820686 0.89972048 0.82985633 0.96886097]
 [0.88026724 0.27656746 0.19866078 0.12736524 0.38194254 0.5887132
  0.31098682 0.79743994 0.4283765  0.56712307]
 [0.87281665 0.84077023 0.28893131 0.92250098 0.66368067 0.37968158
  0.13015126 0.45254554 0.22526722 0.2183409 ]
 [0.81913937 0.97298346 0.32812361 0.68559892 0.17860587 0.96573788
  0.06468047 0.8170758  0.53464112 0.78775683]
 [0.45612528 0.28900168 0.2675324  0.50820293 0.25091049 0.98126818
  0.13730168 0.29704724 0.55221301 0.25312617]
 [0.69448811 0.23518224 0.45958347 0.74846293 0.95515647 0.37439552
  0.10898325 0.03700664 0.16738872 0.91539965]
 [0.83713113 0.13557534 0.86291132 0.42135231 0.53715807 0.83523297
  0.87939424 0.07994136 0.62793675 0.94906768]
 [0.20286292 0.21422664 0.3214591  0.42655275 0.57582877 0.49790319
  0.06823518 0.57200342 0.71871316 0.14334482]
 [0.85412299 0.72310572 0.68763385 0.68986347 0.71221968 0.00441029
  0.9

In [18]:


arr = np.zeros(10)

arr[4] = 1

print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
arr = [1, 2, 0, 0, 4, 0]

rev_arr = arr[::-1]
print(rev_arr)


[0, 4, 0, 0, 2, 1]


In [21]:
# Define size
rows, cols = 5, 5

# Create a zeros array
arr = np.zeros((rows, cols), dtype=int)

# Set borders to 1
arr[0, :] = 1       # Top row
arr[-1, :] = 1      # Bottom row
arr[:, 0] = 1       # Left column
arr[:, -1] = 1      # Right column

print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [22]:

checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1  # Rows 1,3,5,7, columns 0,2,4,6
checkerboard[::2, 1::2] = 1  # Rows 0,2,4,6, columns 1,3,5,7

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#problem3
import numpy as np

# Arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Add
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# Subtract
sub_xy = x - y
print("Subtraction of x and y:\n", sub_xy)

# Multiply x by 3
mul_x = x * 3
print("x multiplied by 3:\n", mul_x)

# Square of each element in x
square_x = x ** 2
print("Square of elements in x:\n", square_x)

# Dot product v and w
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

# Dot product x and v
dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

# Dot product x and y
dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

# Concatenate x and y along rows (axis=0)
concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_xy_row)

# Concatenate v and w along columns (make them 2D first)
v_2d = v.reshape(1, 2)
w_2d = w.reshape(1, 2)
concat_vw_col = np.concatenate((v_2d.T, w_2d.T), axis=1)
print("Concatenate v and w along columns:\n", concat_vw_col)






Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
x multiplied by 3:
 [[ 3  6]
 [ 9 15]]
Square of elements in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


In [29]:
#Problem 4 (Matrix Operation)

# Arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Multiply A and A_inv
result = np.dot(A, A_inv)

print("A × A⁻¹:\n", result)

# Identity matrix for comparison
I = np.eye(2)
print("Identity matrix:\n", I)

# Check if equal
print("Is A × A⁻¹ is identity matrix", np.allclose(result, I))
AB = np.dot(A, B)
BA = np.dot(B, A)

print("A × B:\n", AB)
print("B × A:\n", BA)
print("Is A × B equal to B × A?", np.array_equal(AB, BA))


AB_T = (np.dot(A, B)).T
B_TA_T = np.dot(B.T, A.T)

print("(AB)ᵀ:\n", AB_T)
print("Bᵀ × Aᵀ:\n", B_TA_T)
print("Is (AB)ᵀ equal to Bᵀ × Aᵀ?", np.array_equal(AB_T, B_TA_T))

# Coefficient matrix A
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

# Constants vector B
B_eq = np.array([-1, -3, 9])

# Compute inverse of A_eq
A_inv_eq = np.linalg.inv(A_eq)

# Solve for X
X = np.dot(A_inv_eq, B_eq)

print("Solution [x, y, z]:", X)




A × A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix:
 [[1. 0.]
 [0. 1.]]
Is A × A⁻¹ is identity matrix True
A × B:
 [[23 13]
 [51 29]]
B × A:
 [[36 44]
 [13 16]]
Is A × B equal to B × A? False
(AB)ᵀ:
 [[23 51]
 [13 29]]
Bᵀ × Aᵀ:
 [[23 51]
 [13 29]]
Is (AB)ᵀ equal to Bᵀ × Aᵀ? True
Solution [x, y, z]: [ 2.  1. -2.]
